# Site settings
title: 四海玻璃
email: cnnqjban521@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sihaiboli.github.io" # the base hostname & protocol for your site

twitter_username: 陈维真(13703499110)
github_username: Zhao Yihao

# Build settings
markdown: kramdown
